name: Génération automatique des stats NBA

on:
  schedule:
    - cron: '0 4 * * *'        # Tous les jours à 4h UTC
  workflow_dispatch:           # Permet de lancer à la main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script Python
        run: python script/generate_stats.py

      - name: Commit du fichier JSON mis à jour
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add data_output/nba_stats.json
          git commit -m "🔁 Mise à jour automatique du fichier JSON"
          git push
